### PR TITLE
Disable button

### PR DESCRIPTION
**Pull request by k3ithl1m**
#909 Fingers crossed

### CODE REVIEW

**Comment by k3ithl1m** [comment]
@xavier-villelegier Thanks for being so patient with my contributions and PR. It's my first time contributing so I'm trying to learn and get it right as much as I can. I think when I reforked the whole repo. I only saw master on the branches I have. I wasn't sure how to get the next branch into my git, so I get upstream, and wrote git merge upstream/master, but there still wasn't a next branch, so I just checkout -b from master. I'm assuming that part was what caused the problem. How should I approach this, if you dont mind giving me some advice.

**Comment by k3ithl1m** [comment]
@xavier-villelegier So I tried again, and this time, I forked the repo. And then set a remote upstream to this repo. I then:
`git checkout -b next`
`git pull upstream next`
`git checkout -b disabledB`

Would this be the correct way now?
If so, should I make another PR?

**Comment by k3ithl1m** [comment]
Thanks Monte9. I will make a new PR as soon as I get through my Linear Algebra Exams ;)

**Comment by iRoachie** [comment]
@k3ithl1m All the best mate, hope you do well

**Pull request closed without merging**
