### PR TITLE
Add pressable icons on left side of list items

### PR DESCRIPTION
**Pull request by Joshuabaker2**

### CODE REVIEW

**Comment by binoy14** [comment]
@Joshuabaker2 Could you please fix the conflicts? Thanks for the PR

**Comment by Monte9** [comment]
@Joshuabaker2 also please add documentation supporting these changes.

**Comment by Joshuabaker2** [comment]
Okay sure thing

**Comment by Monte9** [comment]
@Joshuabaker2 just a heads up. We are planning to release `v0.13.0` in the next couple days. We would love to get this PR merged in before then. 

Let me know if that sounds doable. I can help out too if you are swamped.

**Comment by Joshuabaker2** [comment]
Hey Monte, thanks for the help! Yeah I am pretty busy lately, as seen by the fact that I didn't see the previous comment haha. If you could carry this over the finish line that would be awesome, but let me know if you need clarification.

**Comment by Monte9** [comment]
No worries Josh! Thanks for the quick update. 

I'll make sure this PR lands in the next release. 😉

**Comment by Monte9** [comment]
@binoy14 PR looks good. Merging it in. 

Needs docs to support the added props. Will do so once I merge this into `next`

**Pull request merged**
