### PR TITLE
Platform specific SearchBar (v1)

### PR DESCRIPTION
**Pull request by xavier-villelegier**
## Information

I don't know if this can replace the original SearchBar. For those who want a standard design, the original SearchBar is a good component, and this one can be useful for those who want a platform specific one. Maybe they can both cohabit.

## API

**This component inherits all props of the `v1` Input (made by @Monte9), and, by transitivity, all the props of the official [React Native TextInput](https://facebook.github.io/react-native/docs/textinput.html#props)**

This allows to create a really simple component with just 4 additional props for now:

|     Props    | type  | default | description |
|--------------|-------|---------|-------------|
|`cancelButtonTitle`|string|`null`| **iOS only** Title of the cancel button on the right side|
|   `noIcon`   |boolean|`false`|Hides the `leftIcon` of the `Input` when `true`|
|   `clearIcon`   |boolean|`true`|Displays clear icon button when `true`|
|`showLoading` |boolean|`false`|Shows an `ActivityIndicator` when `true`|
|`loadingProps`|object |`{}`   |Props passed to `ActivityIndicator`|
|`onClearText`|function |`null`   |Callback fired when pressing the clear icon|
|`onCancel`|function |`null`   |Callback fired when pressing the cancel button (iOS) or the back icon (Android)|

## Update applied to `v1` Input

|     Props    | type  | default | description |
|--------------|-------|---------|-------------|
|`leftIcon`|React Native element|`null`|Component displayed on the left side of the `TextInput`|
|`leftIconContainerStyle`|style|`null`|Style applied to the container of the `leftIcon`|
|`rightIcon`|React Native element|`null`|Component displayed on the right side of the `TextInput`|
|`rightIconContainerStyle`|style|`null`|Style applied to the container of the `rightIcon`|

## Preview

Almost pixel perfect iOS 11 design (red lines are here for pixel comparison)
pixelperfectsearchbar

**Example 1**
```jsx
<SearchBar
  showLoading
  placeholder='Search'
/>
```
|iOS|Android|
|---|--------|
|oct -15-2017 15-22-05|oct -15-2017 18-16-03|

## TODO
• Add more props for customization

### CODE REVIEW

**Comment by nathanbirrell** [comment]
How far off is this from making it to a release?

**Comment by Monte9** [comment]
@nathanbirrell glad you asked. I'll review this PR and merge within the next couple days. 

For `v1` release, I'll post updates on this  PR: https://github.com/react-native-training/react-native-elements/pull/711#issuecomment-349650835

**Comment by Monte9** [comment]
This PR will need to be recreated since the /example app has been deleted from the master branch and now lives in it's own repo here: https://github.com/react-native-training/react-native-elements-app#get-started

I suggest cloning that repo and using the submodule to create a PR on the `react-native-elements-app` repo as well as create a new branch and submit this PR from within the submodule for `react-naive-elements`.

**Comment by xavier-villelegier** [comment]
Closed this in favor of #837

**Pull request closed without merging**
