### PR TITLE
Fix withTheme

### PR DESCRIPTION
**Pull request by hedikasmanto**
This is patch withTheme script for exclude updateTheme prop on react-dom (RNW) #1747

### CODE REVIEW

**Comment by xavier-villelegier** [comment]
I don't think it is the way to go. What if you want to update the theme dynamically on the web ?

cc @iRoachie

**Comment by hedikasmanto** [comment]
Yeah. Before I submitted this patch, I have known dynamic theme will not working on web. But currently, I will accept this limitation, and I will search another workaround for dynamic theme purpose. on web

**Comment by xavier-villelegier** [comment]
@hedikasmanto I understand that you would accept this limitation but maybe this is not the case for everyone haha 😅 I don't use React Native Web, but if I do I'd personally rather have a warning that not having this feature.

There is surely a way to avoid this warning without removing the feature. Did you try wrapping a custom component and not passing the `updateTheme` props to the children ? Try to not use the `{...props}` syntax in the wrapped component, because it will spread the `updateTheme` too

**Comment by hedikasmanto** [comment]
First of all, CMIIW! I think if I use wrapped component, I will have to wrap more than one component to use theme from this library, and create many custom components that exclude updateTheme props? or something that I missed ? Please elaborate me.
And finally, If this PR can't be accepted (includes the limitation 😅haha), it's ok. I think I will go with keep warning exists.

**Comment by iRoachie** [comment]
Proper fix released for this in [`v1.2.4`](https://github.com/react-native-training/react-native-elements/releases/tag/v1.2.4)

**Pull request closed without merging**
