### PR TITLE
fixed featuredTitle of Card causing 'undefined fontFamily ...' on And…

### PR DESCRIPTION
**Pull request by LoriKarikari**
screenshot_2017-04-13-13-29-32

### CODE REVIEW

**Comment by binoy14** [comment]
@LoriKarikari Thanks for the PR!

**Comment by bastienff** [comment]
Card element is still breaking the app right out of the box, just by being imported.
I tried to find the root of the problem but i had no luck.

**Comment by binoy14** [comment]
@bastienff This Pull request fixes the issue. We will be releasing this very soon

**Comment by Monte9** [comment]
@LoriKarikari @bastienff should be fixed in the latest release `v0.11.1`
Changelog here: https://github.com/react-native-training/react-native-elements/releases/tag/v0.11.1

**Pull request merged**
