### PR TITLE
Expose wrapperStyle prop on Checkbox

### PR DESCRIPTION
**Pull request by devth**
Fix https://github.com/react-native-training/react-native-elements/issues/1339

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey! Thanks for submitting this so quickly :D.

Just a few additions to be made:
**Docs**:
https://github.com/react-native-training/react-native-elements/blob/next/docs/checkbox.md. You can look at the other props in that file for example

**Types**
https://github.com/react-native-training/react-native-elements/blob/next/src/index.d.ts#L572. You'll need to add a definition in here for the new prop.
`wrapperStyle: StyleProp<ViewStyle>;`

**Comment by devth** [comment]
Thanks for the feedback. Will address these.

**Comment by devth** [comment]
Ok updated with those changes!

**Comment by iRoachie** [comment]
Awesome stuff man! 💯

**Comment by devth** [comment]
Thanks! Does this get auto released on `beta` or something or do I need to wait for the next stable release?

**Comment by iRoachie** [comment]
It'll be in the next beta (beta 6). Should be out in another week or so. Just have to fix the tests with the new Theming update.

You can use the `next` branch if you want these changes right now.
`npm i --save https://github.com/react-native-training/react-native-elements.git\#next`

**Comment by devth** [comment]
Awesome thanks!

**Pull request merged**
