### PR TITLE
Add overlayColor props to tooltip component

### PR DESCRIPTION
**Pull request by cleoreo**
Wanna change the overlay color by props.

### CODE REVIEW

**Comment by iRoachie** [comment]
Closed by https://github.com/react-native-training/react-native-elements/issues/1827#issuecomment-473667123

**Comment by cleoreo** [comment]
I think it is good to have a props for us to change the overlay color easily.
`windowBackgroundColor` cannot fit my needs.

Can you please change your mind to add this in?
My project really needs this feature.

Thanks.

**Comment by ronffy** [comment]
I have the same needs.
I looked at the source code and felt that it would be easy to change the code.
I hope the author can perfect it.

**Comment by iRoachie** [comment]
Refer to https://github.com/react-native-training/react-native-elements/pull/1869

**Pull request closed without merging**
