### PR TITLE
Fix Header docs typo

### PR DESCRIPTION
**Pull request by haruelrovix**
It shouldn't be `containerstyle` but `containerStyle`.

image

### CODE REVIEW

**Comment by iRoachie** [comment]
Oh darn sorry about that. Can you also make the change to https://github.com/react-native-training/react-native-elements/blob/master/website/versioned_docs/version-1.0.0-beta6/header.md

**Comment by haruelrovix** [comment]
Done @iRoachie 👌

**Comment by iRoachie** [comment]
Okay lastly, can you remove the change from docs/header.md and do that in a separate PR?

It's kinda complicated, but in a nutshell documents under the `docs/` folder appear in the next version we roll out. So 1.0.0. Those changes go to the `next` branch.

However 1.0.0-beta6 is already released so we can edit that and push directly to `master`.

Got it?

**Comment by haruelrovix** [comment]
Got it. So that's the workflow for contributing in this repository. Thanks for your guidance @iRoachie ! 👍

**Comment by iRoachie** [comment]
Thanks! No problem at all. Congrats on your first contribution 💯

**Pull request merged**
