### PR TITLE
Card's title numberOfLines

### PR DESCRIPTION
**Pull request by 6axter82**
Add number of lines to Card's title

### CODE REVIEW

**Comment by iRoachie** [comment]
@6axter82 Why'd you close?

**Comment by 6axter82** [comment]
I thought this is how it is done. ooops

**Comment by 6axter82** [comment]
@iRoachie what are the next steps? I just wait till the next release? And after that only I can use the changes. Or I yarn upgrade in my project and can use the changes? Thanks!

**Comment by iRoachie** [comment]
Haven't merged it in as yet but your part is done. Gonna consult with other maintainers on when to release this fix. Thanks

**Comment by iRoachie** [comment]
@6axter82 It's merged into the `hotfixes` branch. We should do a release later this week, but for now you can use the hotfix branch in your project.

`yarn add https://github.com/react-native-training/react-native-elements.git\#hotfixes`

**Pull request closed without merging**
