### PR TITLE
#2091 Honor testID if passed.

### PR DESCRIPTION
**Pull request by TomJKlug**
Honors the Test Id if passed on the image component.

### CODE REVIEW

**Comment by iRoachie** [comment]
Instead just move the line https://github.com/react-native-training/react-native-elements/blob/next/src/image/Image.js#L62 above `{...attributes}`

**Comment by TomJKlug** [comment]
Doing that the test does not pass? Am I missing something?

**Comment by iRoachie** [comment]
The test passes, i'm just suggesting a better way to fix the issue

**Comment by TomJKlug** [comment]
I'm sorry. I am not saying that my current implementation passes. I am saying I applied your fix and the tests no longer pass. 
```
 <ImageComponent
          testID="RNE__Image"
          {...attributes}
          onLoad={this.onLoad}
          style={[
            StyleSheet.absoluteFill,
            {
              width: style.width,
              height: style.height,
            },
          ]}
        />
```

This does not pass.

**Pull request merged**
