### PR TITLE
Allow specifying of selectedButtonStyle in button group

### PR DESCRIPTION
**Pull request by ceckobecko**
Greetings from Bulgaria,
Firstly - Thanks for the great framework.

I've found an issue with the button group and styling.

Since we want to allow the overwriting of styles for selected
button without the need of custom logic. This commit
allows that behavior by introducing a new property -
selectedButtonStyle.

Also include the change in the docs

### CODE REVIEW

**Comment by xavier-villelegier** [comment]
Hey @ceckobecko, greetings from RNE 👋😄
Thanks for the PR!
Maybe we can avoid having `selectedBackgroundColor` + `selectedButtonStyle` by factoring a bit. @iRoachie what do you think?

**Comment by iRoachie** [comment]
2nd that lol. Think we can drop selected background color and just use selected button style

**Comment by ceckobecko** [comment]
Will gladly drop it. with your permission :)

**Comment by iRoachie** [comment]
Sure. I think `selectedButtonStyle` is a lot more flexible, although this will be a breaking change. Cool with you @xavier-villelegier ?

**Comment by xavier-villelegier** [comment]
Sounds good to me! 🤙

**Comment by iRoachie** [comment]
Thanks again!

**Pull request merged**
