### PR TITLE
Updated Dependencies & Docs for Button, Input, SearchBar, ListItem

### PR DESCRIPTION
**Pull request by deadcoder0904**
Closed the other ones since I don't know how to Cherry Pick Commits & Send PRs with different commits. So this PR contains docs for Button, Input, SearchBar & ListItem.

### CODE REVIEW

**Comment by deadcoder0904** [comment]
I'll update the dependencies now.

**Comment by deadcoder0904** [comment]
Ohh I thought all dependencies should be updated. Anyways that won't be much of a change though as we just have to edit `package.json` & generated the `lockfiles` for `npm` & `yarn`

**Comment by xavier-villelegier** [comment]
@deadcoder0904 We discussed with other maintainers, let's just update the dependencies. These are `devDependencies` so they shouldn't impact lambda users. 👍

**Comment by iRoachie** [comment]
I'd really prefer if we could split up this PR. It feels like it's doing too much things at once. Docs, tests, and dependencies

**Comment by deadcoder0904** [comment]
Actually I tried doing that with PR #828 creating another branch & adding commits to it & then pushing but it pushed previous commits too. That's why I didn't add more commits to this.

**Comment by deadcoder0904** [comment]
Hey @Monte9 I just got an email from Open Collective that my expense is rejected & being redirected to read [this](https://opencollective.com/faq#expense). And as far as I can understand I have to fill 2 forms - [Non US resident](https://www.irs.gov/pub/irs-pdf/fw8ben.pdf) & [Invoice](https://docs.google.com/document/d/1ROQA11PaYjGtcie-1Ut8cFV5LCISKipSu8sgsY5U7vw/edit#), is that right ? So which form do I have to upload on OpenCollective ?

**Comment by iRoachie** [comment]
You don't a non us resident form, I'm not from the US either and I've submit expenses before. All you need a is a PayPal account, and a completed invoice.

**Comment by deadcoder0904** [comment]
Cool thanks. But what's the Company Name & Collective Name? Is it React Training & React Native Elements respectively?

**Comment by iRoachie** [comment]
Lol nobody likes forms! Here's one of mine for example

screen shot 2018-01-26 at 4 59 36 pm

**Comment by Monte9** [comment]
@deadcoder0904 thanks for the PR again! Few things I noticed:
1. For now, as I already mentioned on your [previous PR here](https://github.com/react-native-training/react-native-elements/pull/827#issuecomment-359269338), only the Button & the Input docs are ready to be done. The rest fo them are still yet to be merged into the `v1` and hence there is no point documenting those.
2. As far as the dependencies are concerned, as @iRoachie suggested, it's better to make independent changes in different PR's so we can track them down in the future if needed. For now, the changes have been made here: https://github.com/react-native-training/react-native-elements/commit/ad05179753d834cab47f51823c08db5b1bc9398e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
3. I saw that you submitted two open collective expenses for $120 each. Usually the way it works is you need to first wait for the PR to be accepted and merged in, and only then submit an expense. For now, I have rejected both your payments. 

Finnaly, there are too many unnecessary changes in this PR. Kindly create a new PR with only the Button & Input component docs update and we will review & merge those. Sorry for the inconvenience. Hope you understand.

**Comment by deadcoder0904** [comment]
@Monte9 My 1st expense was rejected & I got an email that's why I sent the 2nd one with actual invoice. So how much expense I should submit now ?

I'll send only Button & Input docs now.

**Pull request closed without merging**
