### PR TITLE
Deleted unused var and first attempt to implement name prop in input

### PR DESCRIPTION
**Pull request by giacomocerquone**
According to #1325 this is a first naive attempt to resolve it (didn't even test the code). Naive because I want first to address and discuss some technical details about the "feature" I'm about to implement.

The thing I want to discuss is somehow similar to what semanticUI discussed here https://github.com/Semantic-Org/Semantic-UI-React/issues/623

So the roads I saw are these:

1. We "override" the onChange native method of Input.
  1.1 If we do this, how do we pass the name (or other data we may add in the future)? Through a second parameter? If yes, through the use of what structure? (object, directly a var, an array etc.) 
  1.2 We edit directly the synthetic event of react setting a "e.target.name" manually on the event proxy.

2. We define a new function different from onChange that returns the onChange event plus the name (or any other data). Then the options to pass the name through this new function are those defined above.

I already made a choice in this PR and I'll try to explain why, then we'll discuss pros and cons.

**Option 2**
I believe that creating a new function with a different name would confuse users and make somehow less intuitive the usage of it. So I went for the "override" of the onChange method.

**Option 1.2**
This sounds initially like a nice idea since we would adapt and standardize this thing in order to let devs use this feature just like they use it in the browser. The thing is that this would mean to step over react native's feet: we shouldn't take the place of react native developers and this means that we shouldn't edit core specs.

**Option 1.1**
This is the option I chose for exclusion.
Then I decided to go and pass an object because we may want to enhance the Input component even further in the future and so it would be silly to use a simple var parameter and not define an object or an array that can store multiple values.
Discarded the array idea since naming what are you giving back to the user code is important the structure left was the object.

Tell me yours

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @giacomocerquone can you rebase this from `next`? They're a few conflicts and file changes

**Comment by giacomocerquone** [comment]
I'm on vacation! I'll do it asap

**Comment by iRoachie** [comment]
Hey @giacomocerquone, sorry for late reply. Let's get this wrapped up. 

Still outstanding are:
* Tests - Simple test that when `onChange` is called that name is in the object
* Typings, and Docs - Since we're adding 2 new props you'll need to add them

Let me know if you need any assistance.

**Comment by giacomocerquone** [comment]
@iRoachie doing it just now. I noticed one thing though, you have components like SearchBarBase where I don't know why you don't extend your own input, instead the react-native one. This means that if a user would like to use this feature with that component, he can't and this sounds like a incoherence in the lib.

For now I'd say to change just the input component, ended that, we can refactor the others too

**Comment by iRoachie** [comment]
@giacomocerquone Not sure exactly, but you can get an idea from the typescript definitions. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L1169

**Comment by iRoachie** [comment]
@giacomocerquone Still interested in working on this?

**Comment by giacomocerquone** [comment]
being in vacation I should have some time to push forward this pr, sorry for the delay

**Pull request closed without merging**
