### PR TITLE
Fix SearchBar overlapped issue

### LINKED ISSUE #263: SearchBar clearIcon and showLoadingIcon are overlapped.
If both are present, the loading icon can be given the padding-right
How can it be a solution?

### PR DESCRIPTION
**Pull request by abdurrahmanekr**
Old: 

News:

1. clearIcon && showLoadingIcon 

2. clearIcon && !showLoadingIcon

3. !clearIcon && showLoadingIcon

this PR fix #263 .
cc @binoy14 , @Monte9

### CODE REVIEW

**Comment by binoy14** [comment]
@abdurrahmanekr Thanks for the PR. It looks good, can you update the tests. You can run `npm run test -- -u` to update the snapshots.

**Comment by Monte9** [comment]
The response time on this PR is impressive. GJ @abdurrahmanekr! 👏

**Comment by Monte9** [comment]
@binoy14 let's get this merged in for `v0.13.0`.

**Comment by binoy14** [comment]
And... Done!

**Pull request merged**
