### PR TITLE
Update ButtonGroup.js added lastBorderStyle

### PR DESCRIPTION
**Pull request by Squirre1**
Adding lastBorderStyle for fix similar cases.

buttongroup

### CODE REVIEW

**Comment by Monte9** [comment]
@Squirre1 is this PR no longer relevant? Why close it?

**Comment by Squirre1** [comment]
@Monte9 I have merge conflicts after last update this file

**Comment by binoy14** [comment]
@Squirre1 The changes looks good, can you update the snapshots for the tests so it passes. You can run `yarn test -- --u` or `npm test -- --u`

**Comment by Squirre1** [comment]
@binoy14 Thanks! I did it.

**Comment by binoy14** [comment]
@Squirre1 Thanks for the fix!

**Pull request merged**
