### PR TITLE
Fixed false positioning of Slider Thumb

### PR DESCRIPTION
**Pull request by rawad663**
For Issue GH-1738
- changed style of mainStyles.thumbHorizontal, mainStylesthumbVertical to take height/width into consideration (respectively)
- passed props.trackStyle width/height if provided by user

### CODE REVIEW

**Comment by Monte9** [comment]
Thanks for the fix @rawad663 💯 

That math is always hard to understand just by looking at it. Can you please attach screenshots of what it looks like with your PR. Also, can you try the `orientation="vertical"` and make sure that looks fine too.

**Comment by rawad663** [comment]
Hey @Monte9, I've tested the solution with `orientation="vertical"` and it's worked well with the different width values. Here are the screenshots of both orientations after the fix

screenshot_20190131-124549
screenshot_20190131-124617
screenshot_20190131-124627
screenshot_20190131-124649
screenshot_20190131-124708

**Comment by msevestre** [comment]
@rawad663 What's the dark gray background? Shouldn't it be hidden?
I am going to try it in my project as well to let you know how it looks

**Comment by rawad663** [comment]
@msevestre I don't see how the gray background can be hidden. In your code in GH-1738, you've set the height of the track to 10px and the gray background is shown

**Comment by msevestre** [comment]
@msevestre Yeah that's the bug in my opinion. i want the red part to be wider in your example.
Is there a way to make the red section wider then? As you can see in my example, the gray section was not visible BEFORE the update and it is now. I just changed the track height to something big to show the bug in a clearer way.

**Comment by rawad663** [comment]
I see! you want the colored portion of the track to cover the gray portion too. I definitely add that

**Comment by rawad663** [comment]
The fix is pushed, I added trackStyle to the colored portion
```
<Animated.View
          style={StyleSheet.flatten([
            mainStyles.track,
            orientation === 'vertical'
              ? mainStyles.trackVertical
              : mainStyles.trackHorizontal,
              trackStyle,
            minimumTrackStyle,
          ])}
```

slider-fix

**Comment by msevestre** [comment]
@rawad663 looks great. Going to update my screenshot with the code

**Comment by msevestre** [comment]
YES!! You fixed two bugs: the Thumb not centered and the background! Well done @rawad663 
image

**Comment by iRoachie** [comment]
Thanks for the combined effort here. Amazing 💯

**Pull request merged**
