### PR TITLE
[WIP] added android as default style

### PR DESCRIPTION
**Pull request by piu130**
As discussed [here](https://github.com/react-native-training/react-native-elements/issues/1419) the PR that makes android style as default for all Platforms that do not override the style, expect `ios`.

### CODE REVIEW

**Comment by piu130** [comment]
There are several places like [this](https://github.com/react-native-training/react-native-elements/blob/master/src/header/Header.js#L140), where we have a one liner checking for ios. Should I change it to `Platform.select` or leave it?
This is when the same style (`height` here) is applied to all platforms.

**Comment by iRoachie** [comment]
I think maybe we can leave it. The Platform.select with an empty iOS object looks weird

**Comment by piu130** [comment]
This exmple would change from
```js
height: Platform.OS === 'ios' ? 70 : 70 - getStatusBarHeight()
```
to
```js
...Platform.select({
  ios: {
    height: 70
  },
  default: {
    height: 70 - getStatusBarHeight()
  },
}),
```

How would you prevent an empty iOS object? :)

**Comment by iRoachie** [comment]
Not sure it matters, I don't have a preference once the behaviour is the same. Does getStatusBarHeight() work for RNW?

**Comment by piu130** [comment]
@iRoachie I added default `getStatusBarHeight` value to 0. Now it works.

**Comment by piu130** [comment]
How do I fix codecov? I added tests for `getStatueBarHeight` but it does not change anything.

**Comment by iRoachie** [comment]
Hey @piu130 sorry for the conflicts, had to merge some older PRs that fixed bugs. Can you resolve them?

**Comment by piu130** [comment]
@iRoachie merged. But codecov still not :)

**Comment by iRoachie** [comment]
Hey @piu130 just updating you. Gonna push this back to v1.0.0 because i know more conflicts will come up. Will roll out beta6 this week and then we can continue from there

**Comment by iRoachie** [comment]
Hey @piu130 we just released beta6 so there are a ton of conflicts. Can you resolve them?

**Comment by piu130** [comment]
@iRoachie merged.

**Comment by piu130** [comment]
Need to wait for [this](https://github.com/ovr/react-native-status-bar-height/pull/8) PR. Then bump `react-native-status-bar-height` and remove `statusBar.js`.

**Comment by piu130** [comment]
@iRoachie is it ok if I create a PR for each component so we could merge the small ones faster?

**Comment by iRoachie** [comment]
That works!

**Comment by iRoachie** [comment]
Cause now on next we use [react-native-status-bar-height](https://github.com/react-native-training/react-native-elements/blob/next/package.json#L41) So we don't need have statusBar.js anymore

**Comment by iRoachie** [comment]
Closing this since our convo.

**Pull request closed without merging**
