### PR TITLE
FormInput shake animation

### PR DESCRIPTION
**Pull request by martinezguillaume**
### What is it ?

[ref](https://github.com/react-native-training/react-native-elements/issues/377)
This pr provides a new props to `FormInput` component: `shake`.
With it, you can do things like that (provide error interaction)

juil -12-2017 16-00-05

The prop `shake` is a comparable variable, it can be boolean, object, number, ... everything comparable with `===` comparaison. So, each time `shake` changed and is different than its previous value, it'll shake the input.

### Simple use example
`const errorMessage = null;`
```jsx
<TextInput
  shake={!errorMessage ? false : true}
  ...props
/>
```

If you have an error, for example
`const errorMessage = 'oh god, an error';`
`shake` will be true and it'll shake the input.
To re-shake the input, `shake` needs to be false and true again to trigger the shake.

### Advanced error management
If you want to shake the input each time an error occurs, you can compare objects, numbers or strings instead of a simple boolean.
For example, you can numbered the errors. 
`const errorId = 1;`
```jsx
<TextInput
  shake={errorId}
  ...props
/>
```
With this system, you can trigger shakes consecutively.
Of course, if `errorId` is `null` or `false`, it'll not trigger the shake.

🤠🌵🛁🚲👊🏼

This is a first advancement to animations in this repo I think and require discussions about it, best practices, etc... to have the best optimized modular simple components. It's very very open to the discussion and this pr can be all changed !

🤡👩🏻‍🚀🌊🎧🏍

Thanks to @xavier-villelegier who helped me for this pr 😘

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @martinezguillaume this is a supper cool idea :D I have a question on the implementation. Do you think the shake would be easier to control by using it through a ref?

E.g 
* User enters text, presses submit button
* If error, display error message then call the shake method on the component using refs

So
```
<TextInput ref={ref => this.formInput = ref} />

errorHandler() {
  if(this.state.error) {
    this.formInput.shake()
  }
}
```

This way we get around having to set the shake to false again before we can set it to shake again. 
Thoughts @Monte9 @binoy14 ?

**Comment by martinezguillaume** [comment]
I forgot about this one, the component has a method shake, you can do both ! If you use component class, you can use ref. But if you use functional component and stay in redux logic, you can do it just by props

**Comment by Monte9** [comment]
@martinezguillaume this is a solid PR! 💯 /cc @xavier-villelegier 

@iRoachie I agree with you. called the shake method on the ref seems like the easiest way to do it. Can't wait to try this out. 

Also @martinezguillaume this might interest you. ;) https://github.com/react-native-training/react-native-elements/projects/4#card-3823160

**Comment by Monte9** [comment]
@iRoachie can we merge this into this release? I'd be curious to see how it performs in production. I'll leave it up to you tho.. only if you think it's ready.

**Comment by iRoachie** [comment]
@Monte9 Haha it is interesting. It'll probably need some docs to go along with it though. @martinezguillaume Could you add some usage in the docs?

**Comment by martinezguillaume** [comment]
Yes sure ! I was waiting your agreement ahah 🤛

**Comment by martinezguillaume** [comment]
Yes sure ! I was waiting your agreement ahah 🤛

**Comment by martinezguillaume** [comment]
I updated the docs, please verify and tell me if it's good and understandable ! 😄 thanks !

**Comment by iRoachie** [comment]
@Monte9 @xavier-villelegier  LGTM, final look overs?

**Comment by xavier-villelegier** [comment]
@iRoachie Yep lgtm too 👍

**Comment by iRoachie** [comment]
Awesome! One more thing @martinezguillaume so @Monte9 won't complain :P Can you make a quick example screen of the component in use? You can put in the Example app with the rest of the forms

**Comment by xavier-villelegier** [comment]
Here is the example in the `example` app
juil -26-2017 20-31-28

**Comment by Monte9** [comment]
Lgtm. @iRoachie please merge this in when you are ready.

@martinezguillaume it would be great to get this into `v1` asap. In case you are busy, lmk and I can port this over to `v1` in the next week or so. 

@xavier-villelegier it would be really cool to use this for one of the screens in the `v1 /example` app.

**Comment by xavier-villelegier** [comment]
@Monte9 Yea sure, I'll update the `v1 example/` when the shake input will be on the `v1` branch 👍

**Pull request merged**
