### PR TITLE
Add onClearText props so it is able to ejecute a callback when the text i…

### PR DESCRIPTION
**Pull request by delvallejonatan**
…s clear

### CODE REVIEW

**Comment by binoy14** [comment]
@delvallejonatan Take a look at the latest change which was merged. It calls onChangeText due to bug in react native. https://github.com/react-native-training/react-native-elements/blob/next/src/input/Search.js#L23 Is this PR still relevant ?

**Comment by delvallejonatan** [comment]
I think this may work, thanks. How can I get this version ?

**Comment by binoy14** [comment]
We will be release new version later this evening. It will be part of that fixes. If you want to experiment, check out the `next` branch

**Comment by Silvercast** [comment]
I think having an extra props `onClearText` makes sense. How can we know if user deletes all characters, or he removes the last character, or he taps on the clear button?

Some other conversation here https://github.com/react-native-training/react-native-elements/issues/389

**Pull request closed without merging**
