### PR TITLE
added featuredTitle prop to Card component

### PR DESCRIPTION
**Pull request by Monte9**
Read issue #188 for context. 

Updated Card Component API:
1. pass in `title` prop to render `Card Title` (OPTIONAL) (renders regardless of whether image is present or not)
2. pass in `featuredTitle` prop to render title over the image (OPTIONAL) (only works if `image` prop is present)
3. pass in `featuredSubtitle` prop to render subtitle over the image (OPTIONAL) (only works if `image` prop is present)
4. renders all the children within the card component (OPTIONAL)

screen shot 2017-03-19 at 12 41 02 pm

``` js
<Card
  title='FEATURED CARD'
  featuredTitle='REACT NATIVE'
  featuredSubtitle='The idea with React Native Elements is more about component structure than actual design.'
  image={{uri:'http://cdn2.greatfon.com/uploads/picture/453/132/132453/tropical-paradise-beach-coast-2406.jpg'}}>
  <Button
    icon={{name: 'code'}}
    backgroundColor='#03A9F4'
    buttonStyle={{borderRadius: 0, marginLeft: 0, marginRight: 0, marginBottom: 0}}
    title='LEARN MORE' />
</Card>
```
screen shot 2017-03-19 at 12 41 12 pm

``` js
<Card
  featuredTitle='REACT NATIVE'
  image={{uri:'http://cdn2.greatfon.com/uploads/picture/453/132/132453/tropical-paradise-beach-coast-2406.jpg'}}>
  <Text style={{padding: 10}}>The idea with React Native Elements is more about component structure than actual design.</Text>
  <Button
    icon={{name: 'code'}}
    backgroundColor='#03A9F4'
    buttonStyle={{borderRadius: 0, marginLeft: 0, marginRight: 0, marginBottom: 0}}
    title='LEARN MORE' />
</Card>
```
screen shot 2017-03-19 at 12 41 18 pm

``` js
<Card
  image={{uri:'http://cdn2.greatfon.com/uploads/picture/453/132/132453/tropical-paradise-beach-coast-2406.jpg'}}>
  <Text style={{paddingLeft: 10, paddingTop: 10, fontSize: 16, fontWeight: 'bold'}}>REACT NATIVE</Text>
  <Text style={{padding: 10}}>The idea with React Native Elements is more about component structure than actual design.</Text>
  <Button
    icon={{name: 'code'}}
    backgroundColor='#03A9F4'
    buttonStyle={{borderRadius: 0, marginLeft: 0, marginRight: 0, marginBottom: 0}}
    title='LEARN MORE' />
</Card>
```

### CODE REVIEW

**Comment by Monte9** [comment]
@RWOverdijk I am curious to hear your thoughts on this PR. It addresses the suggestion that you made with the `Card` component being able to handle a `featuredTitle` prop.

**Comment by RWOverdijk** [comment]
@Monte9 I'll take a look at this tonight. Am I right to assume this allows you to style the text in the image, too? Position-wise, I mean.

**Comment by Monte9** [comment]
@RWOverdijk did you get a chance to look at it?

**Comment by RWOverdijk** [comment]
@Monte9 I did, and the feature is very useful, but I can't align the text in the image. Other than that, it looks good. 👍

**Comment by binoy14** [comment]
@RWOverdijk `featuredTitleStyle` didn't work for you?

**Comment by RWOverdijk** [comment]
@binoy14 I missed that... Sorry. Looks good. 👍

**Comment by Monte9** [comment]
@RWOverdijk Great! 

Will merge it within the hour! Thanks.

**Comment by RWOverdijk** [comment]
No, thank _you_!

Met vriendelijke groet / Kind regards,

Roberto Wesley Overdijk

SpoonX
Founder

M. +31 (0)6 15 55 32 43 (tel:+31615553243)
W. www.spoonx.nl (http://www.spoonx.nl)
E. wesley@spoonx.nl (mailto:wesley@spoonx.nl)
KvK. 60422696

**Comment by Monte9** [comment]
PR is ready. Merging it now. 

/cc @binoy1 - the readme is not updated in this PR. Hence for Card.js, the readme is outdated. Kindly remind me to update the docs before `v0.11.0` is released. Thanks.

**Comment by RWOverdijk** [comment]
@Monte9 No pushing or rushing, just curiosity: when will 0.11.0 be released?

**Comment by binoy14** [comment]
@RWOverdijk We would be aiming for sometime this coming week given we finish the documentation changes that are needed before we can merge

**Comment by RWOverdijk** [comment]
Ah, thanks! :)

**Comment by Monte9** [comment]
btw @RWOverdijk `v0.11.0` is out. You can now start using the `featuredTile`.

**Comment by RWOverdijk** [comment]
@Monte9 I was going to, yesterday, but because it's not in the docs yet I thought it wouldn't work (I didn't try) I'll try it today! :)

**Comment by Monte9** [comment]
Yeah, the docs for it slipped through the cracks during our major `v0.11.0` release. I'll circle back and add that in this week.

**Comment by iRoachie** [comment]
Docs added in https://github.com/react-native-training/react-native-elements/pull/551/commits/d4958fd681a5399104d01a4351116d622f923733

**Comment by Monte9** [comment]
Thanks a lot @iRoachie! 👍

**Pull request merged**
