### PR TITLE
[ts] Correct style type for IconObject

### PR DESCRIPTION
**Pull request by k3ithl1m**
switch current IconObject type that has defined style?: StyleProp;
to style?: StyleProp;
Would this be right? @xavier-villelegier

### CODE REVIEW

**Comment by xavier-villelegier** [comment]
@k3ithl1m Could you please solve the conflicts by rebasing the `next` branch ?

**Comment by k3ithl1m** [comment]
Sorry @iRoachie , I forgot to turn off auto indent, will fix it

**Comment by k3ithl1m** [comment]
@xavier-villelegier I'm sorry, but what does rebase means? I went back to next branch and change ViewStyle to TextStyle (this time turning off auto indent.) should i make a PR now?

**Comment by iRoachie** [comment]
Don't worry with the rebase, I fixed the changes :)

**Pull request merged**
