### PR TITLE
Create new Avatar component with configurable edit button and status indicator

### PR DESCRIPTION
**Pull request by lsps9150414**
avatar-1
avatar-2

**API:**
```javascript
const propTypes = {
  component: PropTypes.oneOf([
    View,
    TouchableOpacity,
    TouchableHighlight,
    TouchableNativeFeedback,
    TouchableWithoutFeedback,
  ]),
  size: PropTypes.number,
  rounded: PropTypes.bool,
  containerStyle: View.propTypes.style,

  avatarContainerProps: PropTypes.object,
  avatarContainerStyle: View.propTypes.style,

  source: PropTypes.object,
  imageStyle: Image.propTypes.style,

  icon: PropTypes.shape({
    name: PropTypes.string,
    type: PropTypes.string,
    color: PropTypes.string,
    style: View.propTypes.style,
  }),

  title: PropTypes.shape({
    text: PropTypes.string,
    color: PropTypes.string,
    style: Text.propTypes.style,
  }),

  showEditButton: PropTypes.bool,
  onEditPress: PropTypes.func,
  editButton: PropTypes.shape({
    size: PropTypes.number,
    iconName: PropTypes.string,
    iconType: PropTypes.string,
    iconColor: PropTypes.string,
    underlayColor: PropTypes.string,
    style: View.propTypes.style,
  }),

  showIndicator: PropTypes.bool,
  indicator: PropTypes.shape({
    size: PropTypes.number,
    types: PropTypes.arrayOf(PropTypes.shape({
      key: PropTypes.string,
      color: PropTypes.string,
    })),
    status: PropTypes.string,
    style: View.propTypes.style,
  }),
};

const defaultProps = {
  component: View,
  size: 100,
  rounded: false,
  containerStyle: null,

  avatarContainerProps: {},
  avatarContainerStyle: null,

  source: null,
  imageStyle: null,

  icon: {
    name: null,
    type: 'material',
    color: '#fff',
    style: null,
  },

  title: {
    text: null,
    color: DEFAULT_COLORS[3],
    style: null,
  },

  showEditButton: false,
  onEditPress: null,
  editButton: {
    size: null,
    iconName: 'mode-edit',
    iconType: 'material',
    iconColor: '#fff',
    underlayColor: DEFAULT_COLORS[0],
    style: null,
  },

  showIndicator: false,
  indicator: {
    size: null,
    types: [
      { key: 'active', color: 'green' },
      { key: 'inactive', color: 'red' },
    ],
    status: 'active',
    style: null,
  },
};
```

### CODE REVIEW

**Comment by binoy14** [comment]
@lsps9150414 thanks for the PR! Could you please update the tests and then we can review it and merge. Good idea would be have multiple different examples as tests. If you need help with that let me know.

**Comment by lsps9150414** [comment]
@binoy14 Thanks for offering your help! I'm not too familiar with writing tests. Will checkout other components of RNE. Do you have any suggestion which component's test file should I be looking at?

**Comment by lsps9150414** [comment]
@binoy14 Thanks! Will dig into it when I get time.

**Comment by binoy14** [comment]
@lsps9150414 I am gonna close this since it's still a WIP. Please reopen a PR when your ready to get it merged

**Comment by Monte9** [comment]
Oh no! This PR is 💯 

It made the Avatar component great again. But now it's no more. 😢 

Reopening this PR, as it deserves some ❤️

**Comment by Monte9** [comment]
@binoy14 are tests the only thing missing from this PR? If so, let's figure out a way to merge this PR and write tests ourselves.

**Comment by lsps9150414** [comment]
@Monte9 @binoy14 Sorry guys has been too busy lately. It will be great if you guys can add the tests :)

**Comment by binoy14** [comment]
Ya sure we can add the tests. I would suggest merging this into a separate branch and once completed. We will merge that to next. I would say probably after this week's release unless anyone has bandwidth to do it before?

**Comment by Monte9** [comment]
@binoy14 Let's plan to release this in `v0.15.0` (currently on `v0.12.2`). 

Also since this PR adds a lot of enhancements to the Avatar component, we should also make sure the docs are updated appropriately.

Can you take the lead on merging this into a separate branch? Thanks.

**Comment by binoy14** [comment]
@monte9 yup, I'll take of this after this week's release

**Comment by nonotest** [comment]
this is great, can't wait.

**Comment by Monte9** [comment]
@nonotest I am pretty excited about this too. Plan to release this within the next week or two in `v0.14.0`

**Comment by Monte9** [comment]
This PR is long overdue. Merging it into `next` now. 

Couple things are still TODO:
1. Need to update the docs to reflect editButton & loadingIndictor props
2. Need to write additional tests to make sure the new props are tested

Also, I am going to merge this and add demo for the Avatar component on the `example` expo app in this repo. So check that out if you want to see this component in action.

**Comment by Monte9** [comment]
@lsps9150414 I initally merged your PR.. but it actually broke existing functionality. So I had to revert it and manually add the changes myself. 

Also I thought the statusIndicator has a lot of unnecessary complexity to it.. so I decided to leave that out. 

You can see what I added in this commit: https://github.com/react-native-training/react-native-elements/pull/438/commits/85fc216a1a14213665d9c8c79b6b963b6ac6b436

**Comment by lsps9150414** [comment]
@Monte9 Cool thanks for the changes!

**Comment by francisrod01** [comment]
So... I'd like to see this in Avatar component, now don't have it but in the `list_home.js` examples mentioned this use. I don't understand.

**Pull request merged**
