### PR TITLE
if icon is raised, you can scale the shadow

### PR DESCRIPTION
**Pull request by guitar9**
if icon is raised, you can scale the shadow with optional parameter ShadowSize. Which is default 2.

Sometimes some icons are very small and then the default shadow is to big. With ShadowSize you can adjust the perfect size

### CODE REVIEW

**Comment by guitar9** [comment]
why the checks have been failed?

**Comment by iRoachie** [comment]
Hey @guitar9 , You'll have to rebase your PR from the `next` branch. That's where we stage all our changes for the next version.

**Comment by guitar9** [comment]
you changed already the branch?

**Comment by iRoachie** [comment]
Yea, but now your PR has additional changes

**Comment by guitar9** [comment]
okay. The problem is that the Travis CI build failed?

**Comment by iRoachie** [comment]
The travis ci failed, because the snapshots weren't updated for your change. You can read more about our snapshot tests [here](https://react-native-training.github.io/react-native-elements/docs/0.19.0/testing.html#snapshot-testing)

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Pull request closed without merging**
