### PR TITLE
input width changed from 90% to 100%

### PR DESCRIPTION
**Pull request by kevintamarus**
input width changed to 100%, input is offsetting to the left and not centered when at 90%

### CODE REVIEW

**Comment by piu130** [comment]
Doesn't look well but much better than before :) Would be nice to have a 90% width centered input but can't find a way to do this.

**Comment by iRoachie** [comment]
I think the main problem is that the placeholder and text is inset from the container, and that looks weird.

So maybe we can do 100% width on the container style, and remove the marginLeft 10 from the inputStyle

**Comment by iRoachie** [comment]
Hey @kevintamarus  we just released beta6 so there are some conflicts. Can you resolve them or rebase from next?

**Comment by iRoachie** [comment]
Closing as inactive. Feel free to message or create a new issue if this is still a concern.

**Pull request closed without merging**
