### PR TITLE
Bound slider value between min and max

### PR DESCRIPTION
**Pull request by xavier-villelegier**
Refs #1244

### CODE REVIEW

**Comment by iRoachie** [comment]
Finished here?

**Comment by xavier-villelegier** [comment]
Yep

**Comment by iRoachie** [comment]
simulator screen shot - iphone x - 2018-12-07 at 10 18 56

Getting this on iOS, seems the value is null at some point?

**Comment by xavier-villelegier** [comment]
@iRoachie My bad I copy pasted too fast what I did on Snack to fix it. Fixed 👍

**Comment by iRoachie** [comment]
Is this how it's to work? Maybe if the new incoming value is outside the max, min then we should do nothing and not update?

kapture 2018-12-07 at 10 28 20

**Comment by xavier-villelegier** [comment]
The use case here is different, you updates the bounds (`minimumValue` and `maximumValue`), not the value.
This would mean we don't update new max and min from the props if value is not between these two, which is a bit weird to my mind. It means that the user has to take care itself that the value is between the bounds, otherwise he won't be able do update the bounds once the value isn't between them anymore

**Comment by iRoachie** [comment]
Ahh you're saying the example from the issue, isn't really a real-world case and just contrived to show that the slider can go out of bounds?

**Comment by xavier-villelegier** [comment]
Everything can be a real world use case haha but yea with this PR the slider cannot go out of bounds by changing dynamically the bounds anymore

**Comment by iRoachie** [comment]
🚢

**Pull request merged**
