### PR TITLE
Button icon needs to be a component

### PR DESCRIPTION
**Pull request by j-mateo**

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey! We have different versions of the library and the implementation is different in one version. Kindly see [this comment](https://github.com/react-native-training/react-native-elements/pull/1131#issuecomment-383406750)

**Comment by j-mateo** [comment]
This is for the latest version of the docs, using the latest version of the library. So unless it hasn't been documented, I would consider it an issue

**Comment by j-mateo** [comment]
https://react-native-training.github.io/react-native-elements/docs/contributing.html#i-m-making-a-change-for-an-existing-doc-on-version-that-s-to-be-released

**Comment by xavier-villelegier** [comment]
@j-mateo Yea you're right this hasn't been fixed in the `Card` docs. Can you please make this change in `website/versioned_doc` for all v1.0.0-betaX` version ?

**Comment by iRoachie** [comment]
My bad! Sorry about that

**Comment by j-mateo** [comment]
Will do

**Comment by j-mateo** [comment]
Done

**Pull request merged**
