### PR TITLE
Update ButtonGroup

### PR DESCRIPTION
**Pull request by vulong23**
- Reorder component's props for better code reviewing
- Add **onPress** default fallback to a empty function  

- Add **containerStyle** default height. Component should display with minimum configuration.
- Rename **containerStyle** to **style** for better end-user intuitive experience
- Add **buttonStyle** as well as default setting
- Rename **borderStyle** to **innerBorderStyle**
- **innerBorderStyle** will be an object which has 2 properties **width** and **color**. This should make end-user experience better as they do not and need not to know about the borderRight thingy.

### CODE REVIEW

**Comment by binoy14** [comment]
@vulong23 Thanks for the Pull Request. We are using containerStyle api usage on all our components. To be consistent I don't think that change is necessary.

 @Monte9 thoughts?

**Comment by vulong23** [comment]
@binoy14 If that is the case, I have already renamed the **style** props back to **containerStyle**. Thank you for pointing me out that.

**Comment by Monte9** [comment]
@vulong23 thanks for the PR.

Couple things:
1. I have changed the base to our next release branch `v0.11.0`. Make sure to resolve all merge conflicts
2. Can you kindly attach a screenshot of what the `ButtonGroup` looks like with and without your changes? This will help users visualize the changes that this PR brings to the `ButtonGroup` component.

**Comment by vulong23** [comment]
@Monte9 I have already resolved the conflicts, as well as prepared an image to introduce the update. Here it is: http://imgur.com/sbZVSxf.
Please review them.

**Comment by Monte9** [comment]
Changes lgtm! Thanks for the attention to detail in the refactoring @vulong23. 👍

**Pull request merged**
