### PR TITLE
Improved styling of documentation

### PR DESCRIPTION
**Pull request by squidfunk**
I'm the author of the Material theme and realized you are using it for your documentation. This PR adds some customizations to the documentation that make it look better and leverages all features of the Material theme.

bildschirmfoto 2017-04-05 um 00 06 27
bildschirmfoto 2017-04-05 um 18 33 33
bildschirmfoto 2017-04-05 um 18 33 42

Thanks for using it, by the way!

### CODE REVIEW

**Comment by binoy14** [comment]
@squidfunk This is awesome! Thank you very much

**Comment by squidfunk** [comment]
Just two more things:

1. To build the theme, you need the `pygments` package for syntax highlighting and `pymdown-extensions` for checkboxes etc. Those packages are listed as install dependencies from [mkdocs-material-1.5.2](https://github.com/squidfunk/mkdocs-material/releases/tag/1.5.2) on (which got released yesterday), so they get installed automatically. I don't know where and how you are building the docs, but you have to make sure that those dependencies are installed. Instaling 1.5.2 will install them automatically.

2. I noticed some broken images in your docs, e.g. on the index page due to no-mixed-content policy, i.e. page is served via HTTPS, imgur images are served via HTTP, so Chrome refuses to load them

**Comment by binoy14** [comment]
1. We are using travis to build the docs. Here is a the script https://github.com/react-native-training/react-native-elements/blob/v0.11.0/.travis.yml any input on that would be appreciated.

2. That is a good point. We will need to figure that out. Thanks

**Comment by squidfunk** [comment]
Looks good!

**Pull request merged**
