### PR TITLE
fix android: Cannot add a child that doesn't have a YogaNode to a par…

### PR DESCRIPTION
**Pull request by landandan**
…ent without a measure function! (Trying to add a 'RCTRawText [text: ]' to a 'RCTView')

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @landandan could you give some background to this change?

**Comment by landandan** [comment]
@iRoachie 

"react": "16.3.1",
"react-native": "0.55.4",
"react-native-elements": "^1.0.0-beta5"

android: 8.0.0

like this [https://github.com/facebook/react-native/issues/18773](https://github.com/facebook/react-native/issues/18773)

**Comment by herarya** [comment]
guys @iRoachie  how to fix this ? ihave this error, only on android

**Comment by iRoachie** [comment]
Hey could you rebase this PR from next or create it again? Sorry took so long

**Pull request closed without merging**
