### PR TITLE
Fixed <Input> bug that caused errorMessage and label to render an empty string outside of <Text>

### PR DESCRIPTION
**Pull request by kirakik**
Addressed #1136 by checking for an empty string as well as null using the !! (not not) operator.

### CODE REVIEW

**Comment by iRoachie** [comment]
Thanks for sending this in! Looks pretty good to me, just gonna run a test to make sure it doesn't render 'false' sometimes.

**Comment by Gregjarvez** [comment]
`!!("   ")` is `true`. This is not a solid check for empty string. I recommend a regex.

**Comment by kirakik** [comment]
@Gregjarvez `!!(" ")` is not an "empty string" though, a space is considered a character

**Comment by Gregjarvez** [comment]
@kirakik they indeed are. but do we want to render the node with white spaces ?

**Comment by kirakik** [comment]
@Gregjarvez it depends on the use cases we're trying to cover with this. It's common to set the default value of a text to an empty string `""`, but not so common to set it to white spaces `" "`. 

I can see a use case where someone would want to render the `errorMessage` and the `label` regardless of whether or not there is one. For example, two inline `<Input />`s, which need to stay aligned whether or not they both have error messages and/or labels. If we guard against white spaces, this would be difficult to achieve.

**Comment by iRoachie** [comment]
Spaces are valid input. If the user doesn’t want to accept spaces then they can specify that in their on onchange handle

**Pull request merged**
