### PR TITLE
Should show clear icon when value is not empty

### PR DESCRIPTION
**Pull request by vellengs**
should show clear icon when value is not empty when this.props.value;

### CODE REVIEW

**Comment by iRoachie** [comment]
I'm not understanding the purpose of this PR. The iOS SearchBar already does this behaviour.

**Comment by vellengs** [comment]
If I set the search bar value as program set. ( value change event will not trigger) then close icon will not show.(that isn't same with IOS search bar).

**Comment by vellengs** [comment]
image
I want if search bar has value then always show the close icon .

**Comment by iRoachie** [comment]
This is how the SearchBar functions right now. Once there is a value in the SearchBar the close icon shows. This is how the native iOS search bar behaves.

**Comment by vellengs** [comment]
Might show close icon when focus on?

**Pull request closed without merging**
