### PR TITLE
fix travis-ci url and adding codecov button

### PR DESCRIPTION
**Pull request by cpenarrieta**
adding codecov % in readme
fixing build status button url from readme
image

### CODE REVIEW

**Comment by Monte9** [comment]
@cpenarrieta I meant to fix that but never got around to doing it. Thanks. 

Also what are your throught on creating a `testing.md` file with some test related info... 1. How to run them locally. 2. How to write new tests etc. I think we can have this image on there as well. It looks really cool. img

What are your thoughts on this? @cpenarrieta 
/cc @binoy14

**Comment by Monte9** [comment]
Also I put together this comparison. Look at all that green! 😍 
screen shot 2017-04-11 at 9 31 36 pm

**Comment by cpenarrieta** [comment]
Thats a good idea. We can also have a file called `contributing.md` where we explain some of the Contributing Guidelines and how to setup this project locally.

**Comment by Monte9** [comment]
@cpenarrieta Good point. The `contributing.md` file is already being worked on. Check out #282 and feel free to comment on it if you have suggestions. 

/cc @tarang9211 

Also I think creating the `testing.md` file would be appropriate for this PR. Would you like to work on it?

**Comment by cpenarrieta** [comment]
I'll have a busy week. If there is no rush I can start on it next week or this weekend. Is that ok?

**Comment by Monte9** [comment]
@cpenarrieta totally understandable. No rush at all. 

The improved code coverage + codecov change that you contributed will be going live in `v0.11.0` by the end of this week. So thanks for that. 

Once `v0.11.0` is released, we will switch our focus to improving our pipeline + adding more comprehensive documentation + further improving test coverage. So plenty interesting things you can help out with.

**Pull request merged**
