### PR TITLE
Fix button ripple location bug when pressing inner views

### PR DESCRIPTION
**Pull request by xavier-villelegier**
Here is a quick fix for #456. The idea is just to add `pointerEvents='box-only'`, as suggested [here](https://github.com/facebook/react-native/issues/6139#issuecomment-296667951).

|Before|After|
|------|------|
|aout-19-2017 17-11-35|aout-19-2017 17-13-54|

Let me know if it breaks something I didn't see ✌️

### CODE REVIEW

**Comment by martinezguillaume** [comment]
Finally a fix for this ! I didn't even know that a fix exist !




I lov u

**Comment by iRoachie** [comment]
Looks good to me!

**Comment by whimsicaldreamer** [comment]
Is it yet merged with master? How do I get this changes? Am on `"react-native-elements": "^0.17.0",`

**Comment by xavier-villelegier** [comment]
@whimsicaldreamer Yes it was merged, for some reasons it disappeared 🤔 
This has been re-fixed, you can use the `next` branch if you really need this fix, or wait for the next release

**Comment by whimsicaldreamer** [comment]
When can we expect the new release? ☹

**Comment by Monte9** [comment]
@whimsicaldreamer v0.18 is going to be released today (Nov 1st). Be on the look out for it.

**Comment by whimsicaldreamer** [comment]
@Monte9, great! 🎉 waiting for it.

**Comment by Maickonn** [comment]
Excuse me to resurrect this issue, but does anyone know if this problem has really been fixed?

Untitled Project

**Pull request merged**
