### PR TITLE
ESLint error in Text.js Component

### PR DESCRIPTION
**Pull request by rawad663**
- added propType fontFamily in src/text/Text.js
- added defaultProp fontFamily in src/text/Text.js

### CODE REVIEW

**Comment by rawad663** [comment]
After fix:
image

**Comment by iRoachie** [comment]
Hey @rawad663 thanks for spotting this. However font family should be here as a prop. The styles for the text component are passsed i’m through the `style` prop. Instead this PR should remove font family from the props spread on line 
https://github.com/react-native-training/react-native-elements/blob/master/src/text/Text.js#L9

**Comment by rawad663** [comment]
Hello @iRoachie, I haven't realized that fontFamily isn't even used in the file!
I will update the PR removing the references of it.

**Comment by iRoachie** [comment]
Thanks! 💯

**Pull request merged**
