### PR TITLE
feat(Icon): added Stroke ability

### PR DESCRIPTION
**Pull request by kosiakMD**
feat(Icon): added Stroke ability

Added next props:
 - stroke: boolean, default = false;
 - strokeWidth: number, via borderWidth, default = 1;
 - strokeColor: string, via borderColor, default = this.props.color || 'black';

### CODE REVIEW

**Comment by kosiakMD** [comment]
@iRoachie, deleted

**Comment by iRoachie** [comment]
Hey guys @martinezguillaume @Monte9 @xavier-villelegier can I get your thoughts on this? This is a utility over passing a style object over to the Icon. It’s not apart of the react-native-vector-icons Icon props.

**Comment by xavier-villelegier** [comment]
@iRoachie @kosiakMD 
If I understand correctly, this:
```jsx
<Icon
  …
  stroke
  strokeWidth={1}
  strokeColor={'red'}
/>
```
is equivalent to:
```jsx
<Icon
  …
  containerStyle={{
    borderColor: 'red',
    borderWidth: 1,
  }}
/>
```

? If so, I don't know if it is really more intuitive to use a different props to apply styles on the component 🤔

Moreover, this prevents people from factorizing by using the same style across the file by doing
```jsx
<Icon
  …
  containerStyle={styles.icon}
/>
…
const styles = StyleSheet.create({
  icon: {
    borderColor: 'red',
    borderWidth: 1,
  },
})
```

**Comment by Monte9** [comment]
@kosiakMD thanks for the PR! This is a good idea and I can see people using it by passing the stroke props explicitly.

Although I think @xavier-villelegier brings up a good point, i.e by creating explicit props for adding borderWidth & borderColor, it can confuse the user and also make the style less reusable.

Moreover, it adds more lines to the source code instead of keeping the Icon component as lean as possible. 

Again, thanks for the PR, but I think it's better to use containerStyle in order to achieve what you are doing.

**Pull request closed without merging**
