### PR TITLE
[deps] bump jest to fix console variable

### PR DESCRIPTION
**Pull request by drewrothstein**
* Bumps `jest` version to the latest release.

Currently, running `npm test` on OS X 10.13.6 with node `v10.5.0` and npm `6.1.0` results in:
```
  ● Test suite failed to run

    /Users/drew/src/react-native-elements/node_modules/react-native/jest/setup.js: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.
    Invalid variable access: console
...
Test Suites: 23 failed, 23 total
```

Back in April, `jest` fixed this https://github.com/facebook/jest/pull/6075.

Once bumped/installed with `23.5.0`, the tests all pass now:
```
Test Suites: 23 passed, 23 total
Tests:       140 passed, 140 total
Snapshots:   105 passed, 105 total
Time:        7.608s, estimated 36s
```

It looks like you typically bump `package.json` and `package-lock.json` together for a release.  Happy to do whatever you would like here to contribute.

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @drewrothstein this version of jest adds changes the snapshots. Can you updated the snapshots by running `npm test -u`?

**Comment by drewrothstein** [comment]
Sure- not sure the flow here you would like?
Would you like me to merge `next` into my branch and run after an `npm i`?

**Comment by iRoachie** [comment]
You can take a look at https://react-native-training.github.io/react-native-elements/docs/0.19.0/testing.html. Let me know if you're still unsure how to proceed.

**Comment by drewrothstein** [comment]
Sure thing- done.
Looks like one snapshot was updated.

**Comment by iRoachie** [comment]
Thanks @drewrothstein 💯

**Pull request merged**
