### PR TITLE
Button: add the possibility to pass activeOpacity value

### PR DESCRIPTION
**Pull request by HristoEftimov**
The `Button` component is using the default `activeOpacity` which is `0.2`. It will be nice if the developer can pass a custom value for it. 

At the moment, only the `clear: true` property updates it to `0`, which is not enough :/

### CODE REVIEW

**Comment by HristoEftimov** [comment]
@iRoachie, yes, you are right. It's better to move it above the `{...attributes}`. Please, check my last commit :)

**Comment by xavier-villelegier** [comment]
Hey guys @HristoEftimov @iRoachie  `{...atributes}` is already overriding all props, you were looking the `master` branch. This has been fixed on `next` one month ago in https://github.com/react-native-training/react-native-elements/commit/ae0c4132f56a40b67803672392cbf482c0da70a1

**Comment by HristoEftimov** [comment]
@xavier-villelegier okay, but in this case, you cannot pass a custom value for the `activeOpacity` option. Please check: https://github.com/react-native-training/react-native-elements/pull/1269/commits/aae0423e2a6aa6c84aa9cdde417f9955bad02320

**Comment by iRoachie** [comment]
@HristoEftimov In the source that @xavier-villelegier posted, `activeOpacity` would be passed in as apart of the `attributes` object

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
