### PR TITLE
fix(webpack): exlude 'react-native-touchable-scale' from babel-loader…

### PR DESCRIPTION
**Pull request by mgcrea**
… exclusion pattern to allow building to work

With the current setup, I was stuck on the following build issue:

```
ERROR in ./~/react-native-touchable-scale/src/TouchableScale.js
Module parse failed: [...]/react-native-touchable-scale/src/TouchableScale.js Unexpected token (54:6)
You may need an appropriate loader to handle this file type.
| 
|     return (
|       <TouchableWithoutFeedback
|         // todo: pass only TouchableWithoutFeedback's props.
|         {...props}
 @ ./~/react-native-touchable-scale/index.js 1:0-50
 @ ./src/list/ListItem.js
 @ ./src/index.js
```

--- 

EDIT: prettier did auto-fix the `.travis.yml` file, can revert if spacing was intentional.

### CODE REVIEW

**Comment by mgcrea** [comment]
Can't reproduce on the `next` branch, so I guess it has been fixed somehow.

**Comment by iRoachie** [comment]
Cool thanks for follow up

**Comment by mgcrea** [comment]
@iRoachie we might want to consider adding a build as a test step to `.travis.yml` anyway. As currently such errors could become unnoticed by the CI.

**Comment by iRoachie** [comment]
What do you mean to `test` the `.travis.yml`?

**Pull request closed without merging**
