### PR TITLE
Allows to override numberOfLines property in header title.

### PR DESCRIPTION
**Pull request by douglasjunior**
Allows to override numberOfLines property in header title.

### CODE REVIEW

**Comment by xavier-villelegier** [comment]
Thanks for taking the time to do it three times haha 😅

**Comment by douglasjunior** [comment]
No problem. I love to create PRs haha

**Comment by xavier-villelegier** [comment]
@douglasjunior Your fix has been applied to the `hotfixes` branch, that's quite a mess with branches with the upcoming `v1` release, sorry about that!

It should be released later this week but you can use the hotfixes branch if you need it now
```
yarn add https://github.com/react-native-training/react-native-elements.git\#hotfixes
```

**Comment by douglasjunior** [comment]
Ok, thanks. I'm using it directly from my fork for now.

Changing the subject, are you interested in improving the Header to adapt according to the platform? Like [native-base header](https://docs.nativebase.io/Components.html#header-def-headref).

**Pull request closed without merging**
