### PR TITLE
(SearchBar) Allow containerStyle to override lightTheme styles

### PR DESCRIPTION
**Pull request by DaKaZ**
Pretty simple fix for #1352

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @DaKaZ, thanks for submitting this PR. Can you update your branch to base from `next` instead of `master`? `next` branch is where we do all our development.

**Comment by DaKaZ** [comment]
Whoops... sorry about that.  Here is the PR updated to branch off of `next`

**Comment by DaKaZ** [comment]
And... I need to update snapshots...

**Comment by iRoachie** [comment]
Lol correct! Was just about to type that

**Comment by iRoachie** [comment]
Thanks for fixing this! Good job on the first contribution 💯

**Pull request merged**
