### PR TITLE
Migrate View.propTypes to ViewPropTypes

### LINKED ISSUE #413: View.propTypes has been deprecated
I'm using 
- React Native 0.44
- React Native Elements 0.12.2 

and I'm getting the warning "View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead." when using the Button component.

### PR DESCRIPTION
**Pull request by alphasp**
Fix #413

### CODE REVIEW

**Comment by binoy14** [comment]
@alphasp this PR is awesome! Was thinking if we can create a new file with the view prop type so we can just import it instead of duplicating the conditional.

**Comment by alphasp** [comment]
@binoy14 good idea, I updated the PR with new commit.

**Comment by Monte9** [comment]
I'd prefer you just put the `ViewPropTypes.js` file under the `config/` folder.

**Comment by alphasp** [comment]
@Monte9 done

**Pull request merged**
