### PR TITLE
Updated type definitions

### PR DESCRIPTION
**Pull request by renjfk**
* Fixed TooltipProps.toggleOnPress property
* Added toggleTooltip method to Tooltip

### CODE REVIEW

**Comment by iRoachie** [comment]
@AndreiCalazans Is the `toggleTooltip` method supposed to be public?

**Comment by renjfk** [comment]
It should be public in fact I'm actually surprised why it's not even documented. Imagine a scenario like this https://snack.expo.io/@renjfk/rne-tooltip.

**Comment by iRoachie** [comment]
Can you add this usage to the docs as well then? Seems pretty convenient.

See the Interaction Methods section of the SearchBar for example https://react-native-training.github.io/react-native-elements/docs/searchbar.html

**Comment by renjfk** [comment]
This is the best I could come with, feel free to correct.

**Pull request merged**
