### PR TITLE
Should show clear icon  onFocus

### PR DESCRIPTION
**Pull request by vellengs**
Should show clear icon when onFocus value not empty

### CODE REVIEW

**Comment by vellengs** [comment]
#1781 I checked with ios native components like safari search bar,  focus on should show that icon.

**Comment by xavier-villelegier** [comment]
It's already the case. If the searchbar isn't empty, we show the clear icon (it doesn't depend on the focus)
image

Repro https://snack.expo.io/@xavier-villelegier/searchbar-clear

**Comment by vellengs** [comment]
@xavier-villelegier did you make sure the value set program set not initiate value or type to input?

**Comment by Lythenas** [comment]
I can confirm that it is not automatically displayed when changing the value programmatically (at least on android). See  #1846

**Comment by vellengs** [comment]
@Lythenas I did a PR before as check it in render, but that 's real different behavior, sometimes we need not show clear button, but if on editing should be shows that icon button.

**Comment by Lythenas** [comment]
@vellengs currently the clear icon only shows up when you type in the search bar and it stays visible even if it looses focus and disappears when the search bar is empty. But it does not show up when you set the value without the user typing anything.

That would be fixed if instead of having an `isEmpty` state that is set when the value changes, you just check if the value is empty in render. That wouldn't change anything else.

**Pull request closed without merging**
