### PR TITLE
Button & Input docs

### PR DESCRIPTION
**Pull request by deadcoder0904**
Now I'm not submitting anything until this gets merged LOL 😂 
~~Oops noticed the `Button` component just changed, sending another commit~~
And its done 🎉 
@Monte9 You can review this one now

### CODE REVIEW

**Comment by iRoachie** [comment]
@deadcoder0904 Merged and live! Thanks again. cc @Monte9 about open collective

**Comment by deadcoder0904** [comment]
@iRoachie should I send other docs & dependency update that I have already done. Of course if the docs are not ⚠️WIP then I can send the Update Dependencies PR. 

The following things are already done by me & if something has changed it wouldn't require more time to edit either -

 -  Update docs for Search component
 -  Update docs for ListItem component
 -  Update react, react-native & other dependencies (edited)

**Comment by iRoachie** [comment]
The new ListItem isn’t completed yet as it’s still being worked on https://github.com/react-native-training/react-native-elements/pull/866.

The dependencies were already updated in v1.0.0-beta2 while fixing a problem with jest https://github.com/react-native-training/react-native-elements/commit/ad05179753d834cab47f51823c08db5b1bc9398e.

As far as I know the search docs are already updated as @xavier-villelegier updated them when he released the new search bar in https://github.com/react-native-training/react-native-elements/commit/7ee34bb1c70f7cd46dfe6309eb350edbb8dd3589.

**Comment by deadcoder0904** [comment]
Ohh man I worked on it a long time ago. It is too much unclear as the README isn't stating what to work & what not to work. I guess I just wasted my time on that part I guess. Just mention it so that nobody makes the mistake I did bcz I sent a PR #831 a long time ago which never got quick replies so I just pushed more commits. So how much expense should I submit to OpenCollective now ? 

I earlier sent a $130 as I worked on those 4 things, but now somebody sent a PR for the same thing I did.

**Comment by xavier-villelegier** [comment]
Hey @deadcoder0904 

As we're working on the `beta`, things are moving quickly. We were working on these new components, so we couldn't merge your PR combining things that were done (Button, Input), and things that we were developing (SearchBar, ListItem). Each task you can see on the README should correspond to one PR. The `beta1` and `beta2` introduced a lot of new things we've been busy with, that's why in the future, please open 1 PR for 1 task to accelerate the review process.

For the SearchBar and the ListItem cases, I can see that in #831 you updated the docs before the SearchBar and the ListItem were even merged, so your updates weren't reflecting the new features.

I don't think you've wasted your time. You did a great job for the `Button` and the `Input`, thank you for that. If you have a doubt on anything you want to contribute to, you can reach us on [Slack](https://reactnativetraining.herokuapp.com/).

**Comment by deadcoder0904** [comment]
I just need to know the expense & please mention it now in the README that the Updated Dependencies section is done so that someone else doesn't send a PR again.

Also, if something is not done already & is completed, please confirm with me, so I can quickly send a PR now. I just need to make $99 for Apple Dev Account 😉

**Comment by iRoachie** [comment]
Apologize for the confusion

**Comment by deadcoder0904** [comment]
No problem man

**Pull request merged**
