### PR TITLE
WIP: pr/ButtonGroup-DisableSelected

### PR DESCRIPTION
**Pull request by acahir**
As I wasn't sure what practices you follow for snapshots, PR does not include updated snapshots so 5 tests are failing. 

If update to snapshots is not desired, line 53 could be modified to not output "disabled={false}" by default. 

Happy to resubmit with updated snapshots or modified to avoid problem if preference is provided.

  ● ButtonGroup Component › should render without issues

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -18,10 +18,11 @@
         ]
       }
     >
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -71,10 +72,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -124,10 +126,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
      
      at Object.<anonymous> (src/buttons/__tests__/ButtonGroup.js:14:47)

  ● ButtonGroup Component › should have onPress event

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -20,10 +20,11 @@
         ]
       }
     >
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -75,10 +76,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -130,10 +132,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
      
      at Object.<anonymous> (src/buttons/__tests__/ButtonGroup.js:29:47)

  ● ButtonGroup Component › should render selectedIndex

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -18,10 +18,11 @@
         ]
       }
     >
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -71,10 +72,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -130,10 +132,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
      
      at Object.<anonymous> (src/buttons/__tests__/ButtonGroup.js:43:47)

  ● ButtonGroup Component › should render with button.element

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -18,10 +18,11 @@
         ]
       }
     >
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -56,10 +57,11 @@
           <Text />
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
      
      at Object.<anonymous> (src/buttons/__tests__/ButtonGroup.js:55:47)

  ● ButtonGroup Component › should render lastButtonStyle

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -18,10 +18,11 @@
         ]
       }
     >
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -71,10 +72,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
    @@ -124,10 +126,11 @@
           </TextElement>
         </View>
       </TouchableHighlight>
       <TouchableHighlight
         activeOpacity={0.85}
    +    disabled={false}
         onPress={[Function]}
         style={
           Array [
             Object {
               "flex": 1,
      
      at Object.<anonymous> (src/buttons/__tests__/ButtonGroup.js:67:47)

Snapshot Summary
 › 5 snapshot tests failed in 1 test suite. Inspect your code changes or run with `npm test -- -u` to update them.

Test Suites: 1 failed, 28 passed, 29 total
Tests:       5 failed, 126 passed, 131 total
Snapshots:   5 failed, 78 passed, 83 total
Time:        6.768s, estimated 14s
Ran all test suites.

### CODE REVIEW

**Comment by iRoachie** [comment]
@acahir Hey thanks for PR, could you update the snapshots? `npm test -- -u`

**Comment by acahir** [comment]
Snapshots included and flattened into single commit.

**Comment by Monte9** [comment]
@acahir thanks for the PR. 

Could you please update the docs to reflect the addition of the `disableSelected` prop on the `ButtonGroup` components.

**Comment by acahir** [comment]
@monte9 Whoops, of course. I'll merge it into the same commit unless I hear otherwise.

**Comment by Monte9** [comment]
Thanks for your quick response @acahir 👍

**Pull request merged**
