### PR TITLE
Switch from `**` to `Math.pow` for getTooltipCoordinate

### PR DESCRIPTION
**Pull request by dominikeinkemmer**
On my Android phone (Google Pixel 3) I received an error after running `react-native run-android` saying `Unexpected token "*" at ...`. (same as in this closed issue: https://github.com/react-native-training/react-native-elements/issues/1816#issuecomment-473521739)

After doing some painfully long research I found that using `**` instead of `Math.pow` can cause issues in that regard so I when I found that it is used in this project I changed this and my App ran smoothly again.

This PR switches is here to sync this change to `react-native-elements` and changes from `**` to `Math.pow` for `getTooltipCoordinate`.

### CODE REVIEW

**Comment by dominikeinkemmer** [comment]
Seems like the build fails because of the `no-restricted-properties` es-lint rule. If you are interested in merging that change I think that eslint rule has to be removed or adjusted for Math.pow?

**Comment by iRoachie** [comment]
> After doing some painfully long research I found that using ** instead of Math.pow can cause issues in that regard so I when I found that it is used in this project I changed this and my App ran smoothly again.

Where'd you see this issue? Math.pow should function the same as **

**Comment by dominikeinkemmer** [comment]
@iRoachie It happens in my application, when I use the latest version of react-native-elements I always get the Unexpected token `*` error. Once i found the `**` usage in `src/tooltip/getTooltipCoordinate.js` and replaced it with Math.pow instead, the error is gone and things work again.

There is also this issue on the react-native page:
https://github.com/facebook/react-native/issues/11371

The solution proposed by some people to use the `babel-plugin-transform-exponentiation-operator` didn't work for me however.

**Comment by alex4dev** [comment]
I have exactly the same problem since i have updated from 1.0.0beta7 to 1.1.0, replace ** by Math.pow resolve the problem too.
I've seen this issue on my old ipad with iOS9 and on my galaxy S6  on Android 7

**Pull request closed without merging**
