### PR TITLE
Added check for none case in info props of PricingCard.

### PR DESCRIPTION
**Pull request by anushbmx**
As per documentation[1] the PriceCard should be able to work without any content in the info props, this fails because there is no condition check for its value before its its mapped.

*Updated test case for minimum props : removed 'info' as it should work without info.

[1] https://react-native-training.github.io/react-native-elements/docs/0.19.0/pricing.html

### CODE REVIEW

**Comment by anushbmx** [comment]
@xavier-villelegier 👍

**Comment by anushbmx** [comment]
@iRoachie okay, I didn't knew that.

So you want me to do the changes on branch "next" and send pr to that branch or master ?

**Comment by anushbmx** [comment]
@iRoachie new pr #1250

**Comment by iRoachie** [comment]
Yes thank you!

**Pull request closed without merging**
