### PR TITLE
fix #934 - overlay image missing in docs website

### LINKED ISSUE #934: Docs: Overlay image is broken
Link:
https://react-native-training.github.io/react-native-elements/docs/overlay.html
Source:
https://github.com/react-native-training/react-native-elements/blob/master/docs/overlay.md

I didn't find where in the repo you wanted to put the images. There is no `/img` folder. So i didn't do a PR

Here is the image:
https://raw.githubusercontent.com/react-native-training/react-native-elements/ef6aef0c7a240443df2bbe086cfb2548866e3883/docs/images/overlay.png

from this commit https://github.com/react-native-training/react-native-elements/commit/ef6aef0c7a240443df2bbe086cfb2548866e3883

### PR DESCRIPTION
**Pull request by gianpaj**
fix #934 tested with Docusaurus

I selected to merge into the `master` branch. if it should be `next`, then something is not right as the image is there:
https://github.com/react-native-training/react-native-elements/blob/next/docs/images/overlay.png

### CODE REVIEW

**Comment by iRoachie** [comment]
Thanks! @giacomocerquone works great!

**Comment by giacomocerquone** [comment]
Wrong tag? :smile:

**Comment by iRoachie** [comment]
Ha @giacomocerquone which one should it be?

**Comment by giacomocerquone** [comment]
Sorry, I've too many things going on and I think my brain is about to explode my friend. Do you remind me what's this and why you're tagging me?

**Comment by iRoachie** [comment]
Lol oops! I now realize what I did. Sorry!

**Pull request merged**
