### PR TITLE
Fix: paragraphs links in docs

### PR DESCRIPTION
**Pull request by MHase**
I've noticed that some links doesn't work in docs when I want to access specific paragraph, so... here is fixed version :)

### CODE REVIEW

**Comment by iRoachie** [comment]
Which doc version did you encounter this in? The changes you make here will only be available when we release a new version of the docs.

To change existing versions you have to edit the files in `website/versioned-docs`

**Comment by MHase** [comment]
I encountered it on official, public version of [docs](https://react-native-training.github.io/react-native-elements/docs/tooltip.html)

I edited  `next` version of the docs, because it's not so important issue, so I think it can be released with some more minor fixes :)
Or maybe in your opinion should I edit e.g. `website/versioned-docs/version-1.0.0-beta7` ?

**Comment by iRoachie** [comment]
Oh well okay then, it's beta anyway so i guess it's fine.

**Comment by Monte9** [comment]
@MHase As you may (or not) know, we have an [Open Collective](https://opencollective.com/react-native-elements), and we give the money to people that help to contribute to React Native Element. You did a lot of good work recently on RNE, your neat PRs and your issues helped us a lot to polish and improve the v1.0.0 🔥 + you were really comprehensive during the review 🥇 

Sooo, could you please submit a **$50** expense on [Open Collective](https://opencollective.com/react-native-elements)? Here is how to do it:

1. Go on [Open Collective](https://opencollective.com/react-native-elements)
2. Click "Submit Expense"
**Description:** 1.0.0 PRs and issues
**Category:** Engineering

3. For the receipt, use [this template](https://docs.google.com/document/d/1Pc9ic3tbgqqhVUIF-T6QEf8B3d9IVtP_GGnK9LCVcY0/edit?usp=sharing)

Feel free to reach me if you need more details 👌

**Pull request merged**
