### PR TITLE
fix for touchable swipedeck

### PR DESCRIPTION
**Pull request by A**
I found one more bug: `<SwipeDeck />` ignores move-gestures if card is `<TouchableOpacity />`.

```
<SwipeDeck
  data={cards}
  renderCard={this.renderCard}
  onSwipeLeft={() => console.log('to repeat')}
  onSwipeRight={() => console.log('known')}
/>
```

```
// Card
<TouchableOpacity
  onPress={() => this.setState({
    isFlipped: !this.state.isFlipped
  })}
>
  <Text>{title}</Text>
  { isFlipped && <Text>{content}</Text> }
</TouchableOpacity>
```

Here is small fix:
ezgif-1-f083c919a0

### CODE REVIEW

**Comment by A** [comment]
Sorry for the coverage decreasing. But I'm not skilled enough yet to fix it  :(

**Comment by binoy14** [comment]
@A Thanks for the PR! I'll let @Monte9 Review this

**Comment by A** [comment]
Hello @Monte9! Could you help to review this PR?

**Comment by Monte9** [comment]
Thanks for the PR @A. Merging this in for now. 

if you have some more time, please feel free to address #418. Thanks.

**Pull request merged**
