### PR TITLE
Add isEmpty check to onFocus of the Search Bar

### LINKED ISSUE #1846: Android SearchBar clear button now visible when changing value prop
**Explain what you did**

I'm setting the value of the search bar after it is first displayed.

**Expected behaviour**

The clear button should appear if the value is not empty.

**Describe the bug**

The clear button does only appear if the user changes the text but not when changing the text programmatically.

**To Reproduce**

https://snack.expo.io/B1fr1vquN

**Possible Solution**

This seems related to #1247 and looks like an easy fix. Don't only set `isEmpty` in the constructor and onChange. Check it dynamically in render.

**Your Environment (please complete the following information):**

| software              | version |
| --------------------- | ------- |
| react-native-elements |    1.1.0     |
| react-native          |     0.59.1    |
| npm or yarn           |     yarn 1.12.3    |

### PR DESCRIPTION
**Pull request by M-Jas**
## What does this PR do?
- Updates the ```onFocus``` function in the Search Bar(iOS & Android) to set the state of the ```isEmpty``` prop to show the the Clear icon when the Search Bar becomes focused when an initial value is given.

## Any background or context you want to provide?
- The search bar only sets the ```isEmpty``` state in the constructor and in the```onChangeText``` function. We ran into an issue were a value is given to the Search Bar(via redux/prop passing) after the Search Bars has already mounted, the user would focused the Search Bar and the clear icon would not be displayed until they changed the text in the input.

## Expected vs Actual
- Expected: As a user when I'm taken to a new screen with the search text/value is presented in the new Search Bar, and when I focus the search bar and I can press the the clear icon to start a fresh search.
-Actual: The user focuses the search bar and no clear icon is present.

## Images & Gifs
- Before focus on a new search bar with a value give via props
Screen Shot 2019-04-18 at 9 08 38 AM

- After focus on a new search bar with a value give via props(w/o pr changes)
Screen Shot 2019-04-18 at 9 09 03 AM

- Expected After focus on a new search bar with a value give via props
Screen Shot 2019-04-18 at 9 10 01 AM

Fixes #1846

### CODE REVIEW

**Comment by DominicSherman** [comment]
This would fix a bug we have in our app. Anything we can do to help get this merged?

**Comment by bmitchinson** [comment]
Anything else preventing this from being merged?

**Comment by iRoachie** [comment]
Closing in favour of https://github.com/react-native-training/react-native-elements/pull/1995 which removes it from state completely

**Comment by iRoachie** [comment]
Sorry reopening. This is the correct behavior.

**Comment by M-Jas** [comment]
@iRoachie I'll try and get to it today before EOD. I'll shoot you another comment if I fall behind.

**Comment by M-Jas** [comment]
JK I just knocked this out! Let me know if we need anything else.

**Comment by iRoachie** [comment]
Thanks everyone 💯 Sorry took so long.

**Pull request merged**
