### PR TITLE
(Button) Remove borderRadius change from disabled style

### LINKED ISSUE #1278: Button with loading props turns into a grey box on Android only
**Explain what you did**
Using 1.0.0.beta5
I have a view with a Button. The loading prop is set according to some state in the component

**Expected behaviour**
When the loading prop is set, I am expecting the button style to stay the same albeit with a loading indicator. This is the behavior in iOS and was the behavior on Android until I updated from beta2 to beta2

**Describe the bug**
On android, the button with loading prop set to true forgets about button style and becomes square
I tried to set the `loadingSyle` explicitely but it does not change anything

**Screenshots**

IOS:
image

image

Android:

image

image

My button looks like so

```
<Button
              buttonStyle={styles.signInButton}
              containerStyle={styles.signInButtonContainer}
              activeOpacity={0.8}
              title={t('signIn')}
              onPress={this.signIn}
              textStyle={styles.loginTextButton}
              loading={isAuthenticating}
              disabled={isAuthenticating}
            />
```
with
```
 signInButton: {
  borderRadius: 30,
  height: 50,
  width: 200,
  backgroundColor: colors.primary,
  },
```
| software | version |
| -- | -- |
| react-native-elements |1.0.0.beta5 |
| react-native |0.55.4 |
| npm or yarn |yarn |

I am not really sure what else to try at that stage,

Cheers,
Michael

### PR DESCRIPTION
**Pull request by msevestre**
Fixes #1278

### CODE REVIEW

**Comment by msevestre** [comment]
FYI @xavier-villelegier

**Comment by xavier-villelegier** [comment]
Refs #1278

**Comment by msevestre** [comment]
@xavier-villelegier no problem.
Quick question. PR should be made off master or next? Or do you guys decide where this should go?

**Comment by xavier-villelegier** [comment]
@msevestre PR should be based on `next`, this is our dev branch. All features/fixes for the next release are on the `next` branch. When we release, we merge `next` into `master` 🙌
The current PR for the next beta is #1193

**Pull request merged**
