### PR TITLE
adding zIndex, fix swipedeck elevation problem on android devices

### PR DESCRIPTION
**Pull request by Bersam**
fixes https://github.com/react-native-training/react-native-elements/issues/418

### CODE REVIEW

**Comment by Bersam** [comment]
I don't have access to iOS devices, so I've no idea about changes that this cause on iDevices.

**Comment by wuyunqiang** [comment]
I change coe to style={[styles.cardStyle, {zIndex: 1}]} is not work.
but change to style={[styles.cardStyle, {zIndex: 0}]} will be ok on android devices.

**Comment by Bersam** [comment]
I have nexus 5 with android 7.1.2, any zIndex works. but i thought zIndex 1 is more natural.
"react": "16.0.0-alpha.12",
"react-native": "0.46.1",
"react-native-elements": "^0.14.0",
"react-native-vector-icons": "^4.2.0"

**Comment by Monte9** [comment]
@Bersam @wuyunqiang thanks for the fix. 1 thing you could do in the future is to fix the tests as well. All you do is run `npm test -- -u`

Also I'll update the `zIndex: 0` as that's the only case that works on both devices.

**Comment by Manoj002** [comment]
{zIndex: 0} worked for me 
thanks guyss

**Pull request merged**
