### PR TITLE
updated react native elements version to 0.54

### LINKED ISSUE #1180: Update to react-native 0.54 at least
dependencies : 
In order to match at least Expo sdk 26, would it be possible to update to react-native 0.54 instead of 0.52.2 ?
Thank you

### PR DESCRIPTION
**Pull request by Gregjarvez**
closes #1180

### CODE REVIEW

**Comment by Gregjarvez** [comment]
fantastic. I will update them

**Comment by iRoachie** [comment]
Hey @Gregjarvez  let's update the snapshot and get this merged in.  Run `npm run test -- -u`

**Comment by Gregjarvez** [comment]
@iRoachie I did that and no snapshots were updated

**Comment by Gregjarvez** [comment]
Okay. snapshots updated now. I have a few tests failing. I will fix them and make a PR

**Comment by iRoachie** [comment]
Merged!!

**Pull request merged**
