### PR TITLE
Added to SocialIcon

### PR DESCRIPTION
**Pull request by alburdette619**
I added several icons to the `SocialIcon` element including `envelope` for email, `reddit-alien` for reddit, `stack-overflow`, `etsy`, and `steam`.  Also added to the docs to reflect the changes.

Additionally, I alphabetized the `colors`, props deconstruction, and docs type listings.  If this needs to be reverted for the merge I understand but I believe it makes it a better U/DX when lists get this long.

### CODE REVIEW

**Comment by iRoachie** [comment]
This is such an awesome PR. Can you also add them into the example app? The file is here https://github.com/react-native-training/react-native-elements/blob/master/example/src/views/buttons_home.js

**Comment by alburdette619** [comment]
Currently the `SocialIcon`s featured in the example app only consist of 10 of the possibilities.  Would you like me to add everything that's missing or just the 5 I added on another row?

**Comment by alburdette619** [comment]
I went ahead and added them all.

**Comment by iRoachie** [comment]
Fantastic job man! 🎉 Thanks again

**Pull request merged**
