### PR TITLE
Added notice to tile.md. Mentions relation with native touchables

### PR DESCRIPTION
**Pull request by Gregjarvez**
Ref https://github.com/react-native-training/react-native-elements/issues/964

### CODE REVIEW

**Comment by iRoachie** [comment]
Hey @Gregjarvez Thanks for making the PR! Can you also make the change to https://github.com/react-native-training/react-native-elements/blob/master/website/versioned_docs/version-0.19.0/tile.md ?

The change you made will affect all future versions of docs. However since we already versioned `0.19`, then you'll have to change it there as well

**Comment by Gregjarvez** [comment]
@iRoachie I have added the notice to https://github.com/react-native-training/react-native-elements/blob/master/website/versioned_docs/version-0.19.0/tile.md as requested.

**Comment by iRoachie** [comment]
You can test the changes you made by:
`cd react-native-elements/website`
`npm install`
`npm start`

**Comment by Gregjarvez** [comment]
@iRoachie I am unsure why that happened but i removed text wraps and also some test are failing although i have touched those files

**Comment by Gregjarvez** [comment]
@iRoachie that fixed it for me. do you still have the text breaking onto two lines ?

**Comment by iRoachie** [comment]
Hey @Gregjarvez, not sure what happened with the history between branches. Can you over your PR but instead make base it from `master` instead of `next`?

**Comment by Gregjarvez** [comment]
sure I will. @iRoachie

**Comment by iRoachie** [comment]
Closed in favor of #969

**Pull request closed without merging**
