### PR TITLE
fix: onClear for default searchbar

### PR DESCRIPTION
**Pull request by LouisJS**
handle `onPress` method of clearIcon on `SearchBar-default`

### CODE REVIEW

**Comment by LouisJS** [comment]
Unfortunately i have no idea how to test it.

```
it('should render with a custom methods', () => {
    const onChangeTextMock = jest.fn();
    const onClearMock = jest.fn();
    const component = shallow(
      <SearchBar onChangeText={onChangeTextMock} onClear={onClearMock} />
    );

    expect(component.length).toBe(1);
    expect(toJson(component)).toMatchSnapshot();
  });
```
Seems like it is already tested, isn't it ?

**Comment by xavier-villelegier** [comment]
@LouisJS My bad, actually this test is useless for the `clear` method as the `clearIcon` is rendered when the Input isn't empty. I'll have to do another test for that anyway.

**Comment by iRoachie** [comment]
We should probably nmake a list of things we need to write tests for 😄

**Comment by xavier-villelegier** [comment]
@iRoachie Sure haha, I'll open an issue for that

**Comment by LouisJS** [comment]
Wouhou. First contribution into this Open Source Project 💯
Hope it will the first of a long list 💪

**Pull request merged**
